### PR TITLE
Upgrade requirement to php 7.2

### LINKED ISSUE #303: Migrate to PHP 7.2 and test on PHP 7.3
PHP 7.1 will reach end-of-life on December 1, 2019 (source: https://www.php.net/supported-versions.php). 

Is mandatory to switch to PHP 7.2 has is actively supported and will receive security fixes for another year.

The best would be to start testing the code also on PHP 7.3 to make easier the switch process.

### PR DESCRIPTION
**Pull request by hulkur**
## What does this PR do?

Upgrade requirement to PHP 7.2
Update tests

### Related issues

Related to #303 

### Review checklist

* [ ] Are unit tests required?
* [ ] Are Documentation changes needed?

**Before merging**

* [ ] Is history cleaned up? (or can be squashed on merge?)

### CODE REVIEW

**Comment by avvertix** [comment]
The last pipeline seems to fail because of a code style error. Maybe run ` ./vendor/bin/php-cs-fixer fix` and verify that you don't have custom code style rules applied.

```
$ ./vendor/bin/php-cs-fixer fix --dry-run
Loaded config default from "/home/travis/build/k-box/k-box/.php_cs".
   1) k-box/app/Jobs/PreparePersonalExportJob.php

Checked all files in 8.289 seconds, 20.000 MB memory used
The command "./vendor/bin/php-cs-fixer fix --dry-run" exited with 8.
```

**Comment by avvertix** [comment]
I'm going to review all the changes and run all the tests locally.

**Comment by avvertix** [comment]
I changed the base branch from `master` to `upgrade-to-php-72` since forcing the minimum required version to `^7.2` breaks the docker image build pipeline (relies still on php 7.1 heavily).

I also have some local failures I'm going to investigate, but Travis CI seems happy, so it must be related to something local I do not have in my PHP 7.2 installation.

**Comment by hulkur** [comment]
I had to install Imagick and gdal to get some of the things working and video processing does not create `_audio` and `_video` files

**Comment by avvertix** [comment]
Are you using Windows or Linux?

**Comment by hulkur** [comment]
Mac :)

**Comment by avvertix** [comment]
That's interesting because I never tested the development setup on Mac.

**Comment by hulkur** [comment]
All the remaining problems I still have locally are due to external problems. As far as code is concerned, all tests pass.

**Comment by avvertix** [comment]
Yes, seems so also with my local problems. I will squash and merge into the new local branch `upgrade-to-php-72` so I can work on the Docker image without affecting other contributors.

Thanks for your contribution.

**Pull request merged**
