### PR TITLE
Add explicit button instead of checkmark to remove consent

### PR DESCRIPTION
**Pull request by avvertix**
## What does this PR do?

Add explicit button instead of checkmark to remove consent

**original**

image

**changed**

image

image

### Review checklist

* [ ] Are unit tests required?
* [ ] Are Documentation changes needed?

**Before merging**

* [ ] Is history cleaned up? (or can be squashed on merge?)

### CODE REVIEW

**Comment by shenriod** [comment]
Maybe "...to collect *anonymous* statistics..." ?

And I *think* the correct English phrasing is "help us improve..." (Without "to")

And a short text / field telling explicitly if the statistics collection is currently "enabled" or "disabled"? It is redundant of course but I feel it makes everything clearer

**Comment by avvertix** [comment]
> Maybe "...to collect anonymous statistics..." ?

yes, should be included for clarity

> And I think the correct English phrasing is "help us improve..." (Without "to")

I was having the same doubt

> And a short text / field telling explicitly if the statistics collection is currently "enabled" or "disabled"? It is redundant of course but I feel it makes everything clearer

Yes, a bit redundant, but probably is worth to tell in plain sight the current state

**Comment by avvertix** [comment]
@shenriod something like this?

image

**Comment by shenriod** [comment]
Perfect!

**Pull request merged**
