### PR TITLE
#306 - Upload hint message fix

### PR DESCRIPTION
**Pull request by joaopjt**
## What does this PR do?

Fix upload hint message appearing when moving documents, already uploaded.

### Related issues

None.

### Review checklist

* [ No ] Are unit tests required?
* [ No ] Are Documentation changes needed?

**Before merging**

* [ Yes ] Is history cleaned up? (or can be squashed on merge?)

### CODE REVIEW

**Comment by joaopjt** [comment]
Back again. I`ve pushed some more fixes, this time basic style things.
The items that are together with the main fixes are:

- Letter centering on Avatar circle.
- Action buttons align, centering and a minor cursor bug fix.
- Dropdown content shadow and position fix.
- Logo being hidden in mobile screen (broken mobile screen bug fix).

Some screenshots:
Header update:  https://prnt.sc/poklcq
Mobile view: https://prnt.sc/pokmey

**Comment by avvertix** [comment]
@joaopjt please separate all style related changes to their own pull request as this one should only contain fixes for #306 

Take also in consideration that changes to less files do not have anymore impact on the UI as all is now controlled via Tailwind and the `app-evolution.css` file

**Comment by joaopjt** [comment]
Got it.

The app-evolution.css is the final bundled css file, right?
I've have forgotted to added to the pull, but i will make sure to fix this one on the next.
I'll not make a issue for the styles upload. After the #306 PR approve, i open the styles PR to get all from master

**Comment by avvertix** [comment]
> The app-evolution.css is the final bundled css file, right?

is the file that references all the required CSS and is the file that PostCSS will process to generate the final bundle that is then added to the `public` folder.

**Pull request closed without merging**
