### PR TITLE
#306 - Upload hint message fix

### PR DESCRIPTION
**Pull request by joaopjt**
## What does this PR do?

Fix the upload hint message for files already listed in the box.

### Related issues

#306 

### Review checklist

* [ No ] Are unit tests required?
* [ No ] Are Documentation changes needed?

**Before merging**

* [ Yes ] Is history cleaned up? (or can be squashed on merge?)

### CODE REVIEW

**Comment by joaopjt** [comment]
Got it, but what is the necessity of drag the collection item from the list?
I guess we can disable it on the html, don't you think?

**Comment by avvertix** [comment]
> Got it, but what is the necessity of drag the collection item from the list?
> I guess we can disable it on the html, don't you think?

It is a feature to allow to change hierarchy of the collection structure otherwise a user will not be able to modify the created collection hierarchy

**Comment by avvertix** [comment]
Are you having troubles with the requested changes. If you need I can do some suggestions directly in the code

**Comment by avvertix** [comment]
Superseded by #400

**Pull request closed without merging**
