### PR TITLE
Migrate to Tailwind and PostCSS for main styles

### PR DESCRIPTION
**Pull request by avvertix**
## What does this PR do?

It is a Work In Progress on an experimental layout change to improve mobile experience and general experience. Since we started including some utility first CSS classes, it was a way to experiment.

**Before**

mobile view (before)

desktop view before

**After**

mobile view

mobile view with opened menu

desktop view

### Review checklist

* [ ] Are unit tests required?
* [ ] Are Documentation changes needed?

**Before merging**

* [ ] Is history cleaned up? (or can be squashed on merge?)

### CODE REVIEW

**Comment by shenriod** [comment]
At first sight (screenshots) I like it a lot!

Are those changes "only" aiming at changing the visual layout and the
responsiveness or will there be also interaction / UX changes (AJAX, etc)?

**Comment by avvertix** [comment]
So far only the improvement of the base layout with a focus on the basic mobile experience.

**Comment by avvertix** [comment]
I changed the title to reflect the main aim, which is moving to utility-first CSS using [TailwindCSS](https://tailwindcss.com/): the main reason are:

- re-organize the styles to be more manageable
- ensure more consistency between changes
- create a set of reusable components
- limit the need of new CSS code for plugins and new features

**Comment by avvertix** [comment]
image

image

**Pull request merged**
