### PR TITLE
Fix #308 Profile update denied if user didn't change the nicename/use…

### LINKED ISSUE #308: Profile update denied if user didn't change the nicename/username
### Short Description of the issue

Adding information on my profile (e.g. Organization) is not possible unless the username/nicename is changed.

### Expected behavior

I can update my profile without changing my username

### Steps to reproduce the incorrect behavior

1. Go to the profile page
2. Add an organization
3. press save

### General information

Version of your K-Box: 0.28.4 and above

URL of the page where the problem has occurred: /profile

Type and version of your browser: 

In what language are you using your K-Box? 

### Screenshots

image

### PR DESCRIPTION
**Pull request by kontoulis**
## What does this PR do?

Allows users to update their profile without changing their username.

### Related issues

Fixes #308 

### Review checklist

* [x] Are unit tests required?
* [ ] Are Documentation changes needed?

**Before merging**

* [ ] Is history cleaned up? (or can be squashed on merge?)

### CODE REVIEW

**Comment by avvertix** [comment]
@kontoulis awesome, thanks for your contribution.

I see the automated checks failure. From a quick look seems that one of the external dependencies failed to download. I'm investigating it in #311

**Comment by avvertix** [comment]
So xpdf tools was failing to download. This is probably the cause for a failure on Travis, if you can rebase on `master` would be super.

**Comment by kontoulis** [comment]
The issue with the rebase commit was that I have different config value on my local phpcs for `concat_space` :)

**Comment by avvertix** [comment]
The coding standard was not really a problem, but glad that you took time to fix it.

Meanwhile I checked the code and tested the changes locally and I confirm that this indeed fixes #308 so I'll let GitHub do the rest

**Pull request merged**
